In [1]:
import torch


In [2]:
m=torch.tensor(
[[1,3,4,2],
[3.0,4,6,1],
[1,6,2,1.0],
[6,7,8,9],
[2,3,4,1]
])

In [4]:
m.shape

torch.Size([5, 4])

In [15]:
m.sum(axis=0)/m

tensor([[13.0000,  7.6667,  6.0000,  7.0000],
        [ 4.3333,  5.7500,  4.0000, 14.0000],
        [13.0000,  3.8333, 12.0000, 14.0000],
        [ 2.1667,  3.2857,  3.0000,  1.5556],
        [ 6.5000,  7.6667,  6.0000, 14.0000]])

In [6]:
m.sum(axis=1)

tensor([10., 14., 10., 30., 10.])

In [18]:
m.sum(axis=0,keepdims=True)/m

tensor([[13.0000,  7.6667,  6.0000,  7.0000],
        [ 4.3333,  5.7500,  4.0000, 14.0000],
        [13.0000,  3.8333, 12.0000, 14.0000],
        [ 2.1667,  3.2857,  3.0000,  1.5556],
        [ 6.5000,  7.6667,  6.0000, 14.0000]])