In [1]:
# 基本的线性代数
import torch
import os

# 矩阵f范数，矩阵各个元素平方和开根号
# 特征向量和特征值，不会被矩阵改变方向的向量。
# Ax = lamba x



In [7]:
# 标量，最简单的

x = torch.tensor([2])
y = torch.tensor([3.0])

x, y

(tensor([2]), tensor([3.]))

In [8]:
x+y, x-y, x*y, x/y


(tensor([5.]), tensor([-1.]), tensor([6.]), tensor([0.6667]))

In [22]:
# 向量，一个列表组建tensor
z=torch.tensor([1,2,4,6])
len(z)
zlist=[]
for i in range(len(z)):
    zlist.append(z[i])
print(zlist)

[tensor(1), tensor(2), tensor(4), tensor(6)]


In [27]:
z.shape

torch.Size([4])

In [31]:
# 矩阵
m = torch.arange(20)
m=m.reshape([5,4])
m

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [38]:
m.T   # 转置


tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [42]:
n = torch.arange(24).reshape([2,3,4])
n

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [50]:
A = torch.arange(40, dtype=torch.float32).reshape(2,5,4)
B=A # 不会分配新内存，会同步修改，所以要用clone
B=A.clone()
A, id(A), id(B)


(tensor([[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.],
          [16., 17., 18., 19.]],
 
         [[20., 21., 22., 23.],
          [24., 25., 26., 27.],
          [28., 29., 30., 31.],
          [32., 33., 34., 35.],
          [36., 37., 38., 39.]]]),
 2796862950768,
 2796862954992)

In [51]:
# 哈达玛积，矩阵元素对应相乘
A * B

tensor([[[0.0000e+00, 1.0000e+00, 4.0000e+00, 9.0000e+00],
         [1.6000e+01, 2.5000e+01, 3.6000e+01, 4.9000e+01],
         [6.4000e+01, 8.1000e+01, 1.0000e+02, 1.2100e+02],
         [1.4400e+02, 1.6900e+02, 1.9600e+02, 2.2500e+02],
         [2.5600e+02, 2.8900e+02, 3.2400e+02, 3.6100e+02]],

        [[4.0000e+02, 4.4100e+02, 4.8400e+02, 5.2900e+02],
         [5.7600e+02, 6.2500e+02, 6.7600e+02, 7.2900e+02],
         [7.8400e+02, 8.4100e+02, 9.0000e+02, 9.6100e+02],
         [1.0240e+03, 1.0890e+03, 1.1560e+03, 1.2250e+03],
         [1.2960e+03, 1.3690e+03, 1.4440e+03, 1.5210e+03]]])

In [53]:
A.sum(axis=0) # 第一个维度求和，也就是把两张 5×4 的矩阵叠加起来

tensor([[20., 22., 24., 26.],
        [28., 30., 32., 34.],
        [36., 38., 40., 42.],
        [44., 46., 48., 50.],
        [52., 54., 56., 58.]])

In [54]:
A.sum(axis=1) # 第二个维度，行求和，列数不变，对应位置行求和

tensor([[ 40.,  45.,  50.,  55.],
        [140., 145., 150., 155.]])

In [55]:
A.sum(axis=2) # 第三个维度求和，行数不变，列相加

tensor([[  6.,  22.,  38.,  54.,  70.],
        [ 86., 102., 118., 134., 150.]])

In [56]:
A.sum(axis=[0,1])

tensor([180., 190., 200., 210.])

In [57]:
A.sum(axis=[1,2]) 

tensor([190., 590.])

In [58]:
A.sum(axis=[0,2])

tensor([ 92., 124., 156., 188., 220.])

In [59]:
A.sum(axis=[0,1,2])

tensor(780.)

In [60]:
A.mean(), A.sum()/ A.numel()  # 均值 = 求和 / 元素个数

(tensor(19.5000), tensor(19.5000))

In [65]:
temp=A.sum(axis=1,keepdims=True)  #保留求和轴的尺寸
temp, temp.shape

(tensor([[[ 40.,  45.,  50.,  55.]],
 
         [[140., 145., 150., 155.]]]),
 torch.Size([2, 1, 4]))

In [66]:
A/temp

tensor([[[0.0000, 0.0222, 0.0400, 0.0545],
         [0.1000, 0.1111, 0.1200, 0.1273],
         [0.2000, 0.2000, 0.2000, 0.2000],
         [0.3000, 0.2889, 0.2800, 0.2727],
         [0.4000, 0.3778, 0.3600, 0.3455]],

        [[0.1429, 0.1448, 0.1467, 0.1484],
         [0.1714, 0.1724, 0.1733, 0.1742],
         [0.2000, 0.2000, 0.2000, 0.2000],
         [0.2286, 0.2276, 0.2267, 0.2258],
         [0.2571, 0.2552, 0.2533, 0.2516]]])

In [81]:
x = torch.arange(4,dtype=torch.float32)
y = torch.ones(4,dtype=torch.float32)
x,y,x*y,torch.mul(x,y), torch.dot(x,y)
# 元素对应积，叉乘，点乘

(tensor([0., 1., 2., 3.]),
 tensor([1., 1., 1., 1.]),
 tensor([0., 1., 2., 3.]),
 tensor([0., 1., 2., 3.]),
 tensor(6.))

In [83]:
# 点乘就是向量元素相乘求和
torch.dot(x,y) == sum(x*y)

tensor(True)

In [84]:
a=torch.arange(20).reshape(5,4)
b=torch.arange(12).reshape(4,3)
a,b

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15],
         [16, 17, 18, 19]]),
 tensor([[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]]))

In [85]:
torch.mm(a,b)  #mm 矩阵相乘， mv矩阵乘向量

tensor([[ 42,  48,  54],
        [114, 136, 158],
        [186, 224, 262],
        [258, 312, 366],
        [330, 400, 470]])

In [96]:
# 向量2范数。使用torch.norm() 要注意数据类型得是浮点
t=torch.tensor([-3,4],dtype=torch.float32)
t, torch.norm(t)

(tensor([-3.,  4.]), tensor(5.))

In [98]:
# 1范数 L1
torch.abs(t).sum()

tensor(7.)

In [105]:
torch.arange(12,dtype=torch.float32).reshape(3,4)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [106]:
torch.norm(torch.arange(12,dtype=torch.float32).reshape(3,4)) # 矩阵默认F范数

tensor(22.4944)

In [107]:
s=torch.ones(2,5,4)

In [111]:
s.sum(axis=0,keepdim=True).shape

torch.Size([1, 5, 4])