In [1]:
import os
import torch
import math

In [2]:
'''
一、概念题
什么是标量、向量和矩阵？
什么是向量的维度？
什么是矩阵的行和列？
什么是线性组合？
什么是线性相关与线性无关？
'''

'''
基础答案
标量是单个数，向量是一维数组，矩阵是二维数组。

向量的维度就是元素个数或长度。

矩阵的行是横向排列，列是纵向排列。

线性组合是若干向量按系数加权后求和。

线性相关表示某些向量可以由其他向量线性表示；线性无关则不能。
'''

'\n基础答案\n标量是单个数，向量是一维数组，矩阵是二维数组。\n\n向量的维度就是元素个数或长度。\n\n矩阵的行是横向排列，列是纵向排列。\n\n线性组合是若干向量按系数加权后求和。\n\n线性相关表示某些向量可以由其他向量线性表示；线性无关则不能。\n'

In [3]:
# 代码题
# 创建一个向量并输出它的 shape。
torch.tensor([1,2,3,4]).shape



torch.Size([4])

In [7]:
# 创建一个 2 x 3 矩阵。
torch.tensor([[1,2,4],[5,6,2]])

tensor([[1, 2, 4],
        [5, 6, 2]])

In [8]:
# 计算两个同维向量的逐元素相加。
a=torch.rand(2,4,5)
b=torch.randn(2,4,5)
a,b,a+b

(tensor([[[0.0306, 0.9983, 0.3304, 0.2595, 0.4780],
          [0.9493, 0.7945, 0.2837, 0.9815, 0.9824],
          [0.5003, 0.7254, 0.9189, 0.4177, 0.8840],
          [0.8052, 0.3441, 0.2628, 0.7257, 0.6505]],
 
         [[0.8769, 0.1380, 0.2989, 0.1166, 0.2301],
          [0.6519, 0.1747, 0.7313, 0.2139, 0.8444],
          [0.3934, 0.1033, 0.1933, 0.8082, 0.8029],
          [0.3632, 0.9229, 0.0559, 0.1392, 0.9508]]]),
 tensor([[[ 1.0009e+00, -2.0314e-03, -5.2993e-01, -1.1831e-01,  5.2518e-01],
          [ 9.8502e-01, -8.9421e-02, -7.6128e-01,  8.5557e-01,  2.3219e+00],
          [ 1.4972e+00,  3.5750e-01,  1.0549e+00, -1.5355e-01,  1.3514e+00],
          [-5.7534e-01,  1.2443e-01,  9.9348e-01,  3.5842e-01, -1.2565e+00]],
 
         [[-1.5538e+00,  1.0612e-01,  2.1420e+00,  1.0284e+00,  1.0303e+00],
          [-1.1849e+00,  6.0178e-01, -1.0011e+00, -8.8972e-01,  5.1240e-01],
          [ 9.3424e-01,  5.3205e-01, -3.1527e-01, -3.3861e-01,  1.1304e+00],
          [ 4.2327e-01,  7.0627e-01,

In [13]:
# 计算向量与标量的乘法。
torch.tensor([6])*torch.tensor([1,2,4])
4*torch.tensor([1,2,4])

tensor([ 4,  8, 16])

In [14]:
# 取出矩阵的第 1 行和第 2 列。
a[:,0,:], b[:,:,1]

(tensor([[0.0306, 0.9983, 0.3304, 0.2595, 0.4780],
         [0.8769, 0.1380, 0.2989, 0.1166, 0.2301]]),
 tensor([[-0.0020, -0.0894,  0.3575,  0.1244],
         [ 0.1061,  0.6018,  0.5320,  0.7063]]))

In [16]:
import numpy as np
# 三、实操题
# 将一个 1 x 6 的张量变成向量。
torch.tensor([1,2,3,4,5,6])

# 用代码表示一个 3 维向量。
# 计算一个矩阵的转置。

# 构造一个对角矩阵。
# 判断两个向量是否可以做加法。


tensor([1, 2, 3, 4, 5, 6])

In [18]:
m=torch.randn(30).reshape(5,6)
n=m.T
m,n

(tensor([[-0.7613,  0.6805,  0.4256,  0.3064,  0.0630,  0.2017],
         [ 1.1048,  1.0306,  0.8524,  1.2017, -0.1991,  0.9249],
         [-0.2647,  0.9465,  0.0527, -0.1718,  0.7644,  1.5127],
         [-2.6304,  1.3689, -0.3961,  1.7678, -3.1860, -1.2058],
         [ 0.0559, -0.2442,  0.3120, -0.3086,  1.1652,  0.6990]]),
 tensor([[-0.7613,  1.1048, -0.2647, -2.6304,  0.0559],
         [ 0.6805,  1.0306,  0.9465,  1.3689, -0.2442],
         [ 0.4256,  0.8524,  0.0527, -0.3961,  0.3120],
         [ 0.3064,  1.2017, -0.1718,  1.7678, -0.3086],
         [ 0.0630, -0.1991,  0.7644, -3.1860,  1.1652],
         [ 0.2017,  0.9249,  1.5127, -1.2058,  0.6990]]))

In [19]:
'''
一、矩阵运算
计算两个矩阵的加法。
计算矩阵和标量的乘法。
计算矩阵转置后的 shape。
解释矩阵乘法和逐元素乘法的区别。
判断两个矩阵是否可以做矩阵乘法。'''


'\n一、矩阵运算\n计算两个矩阵的加法。\n计算矩阵和标量的乘法。\n计算矩阵转置后的 shape。\n解释矩阵乘法和逐元素乘法的区别。\n判断两个矩阵是否可以做矩阵乘法。'

In [23]:
m1=torch.randn(30).reshape(5,6)
m2=torch.randn(30).reshape(5,6)
a=torch.tensor(10000)
m1+m2,m1-m2,m1*m2,m1/m2,a*m

(tensor([[ 0.1298,  2.6723, -0.9075,  0.4193, -0.1473, -1.7975],
         [-0.4307, -1.9220, -0.6683,  0.2950, -2.7277, -1.7937],
         [-1.4236,  1.0942, -0.8105, -0.7794,  0.9936, -1.2817],
         [-0.3508,  0.4935,  1.4131, -0.8689,  1.8831, -2.1270],
         [-0.1954,  0.0294,  0.5079,  1.4006, -0.2576,  1.0624]]),
 tensor([[ 0.1581, -1.1729, -0.8575,  2.3644, -0.2667,  1.9426],
         [-0.5338,  0.8434,  0.2898, -2.7205, -0.8714, -1.7007],
         [-0.0556, -1.8913, -1.0457, -0.5312,  0.3553,  0.4751],
         [ 1.7860,  4.1267, -0.1755,  1.4618, -1.6750,  1.4069],
         [ 1.3249,  0.9393, -0.7302, -1.3085,  1.5518, -0.8631]]),
 tensor([[-2.0372e-03,  1.4414e+00,  2.2074e-02, -1.3537e+00, -1.2359e-02,
          -1.3575e-01],
         [-2.4860e-02,  7.4568e-01,  9.0644e-02, -1.8285e+00,  1.6703e+00,
           8.1318e-02],
         [ 5.0585e-01, -5.9493e-01, -1.0913e-01,  8.1317e-02,  2.1522e-01,
           3.5424e-01],
         [-7.6665e-01, -4.1965e+00,  4.9152e-01, 

In [24]:
m.T.shape

torch.Size([6, 5])

In [26]:
torch.mm(m1,m2.T)

tensor([[-0.0404,  1.6809,  0.6143, -4.3352,  1.1458],
        [ 3.3141,  0.7346,  0.6135,  2.6434, -1.2020],
        [ 0.6991, -0.6376,  0.4526,  3.4530, -1.7171],
        [ 4.8071, -3.0866,  3.3430, -3.9957, -1.2527],
        [ 0.7335, -1.1232,  0.4369, -0.6500, -1.1455]])

In [27]:
'''二、向量运算
计算两个向量的点积。
计算一个向量的 L2 范数。
计算两个向量的夹角余弦。
解释什么是投影。
说明向量点积的几何意义。'''

'二、向量运算\n计算两个向量的点积。\n计算一个向量的 L2 范数。\n计算两个向量的夹角余弦。\n解释什么是投影。\n说明向量点积的几何意义。'

In [38]:
v1.to(torch.float16)
v1.float()

tensor([1., 2., 3., 4.])

In [30]:
v1=torch.tensor([1,2,3,4])
v2=torch.tensor([5,644,4,121222])
torch.dot(v1,v2)


tensor(486193)

In [45]:
torch.norm(v1.float()),  torch.norm(v1.float(), p=2)

(tensor(5.4772), tensor(5.4772))

In [46]:
# 向量点积 = cosα * ||v1|| * ||v2||
cosa = torch.dot(v1,v2)/(torch.norm(v1.float())*torch.norm(v2.float()))
cosa

tensor(0.7323)

In [47]:
# 投影表示一个向量在另一个向量方向上的分量。
# 点积反映了两个向量的相似程度及夹角关系。

In [56]:
# 使用 PyTorch 计算两个向量的点积。
torch.dot(v1,v2)
# 计算矩阵乘法 A @ B。
torch.mm(m1,m2.T), m1@m2.T
# 计算矩阵转置后再做乘法。
# 计算一个矩阵每一行的和。
m1,m1.sum(axis=1)
# 计算向量的范数并打印结果。
torch.norm(m1,p=2)

tensor(4.6628)

In [57]:
'''一、综合应用
构造一个 3 x 3 矩阵，并判断它是否为对称矩阵。
构造一个 2 x 2 矩阵，计算它的行列式。
找出一个矩阵的主对角线元素。
用代码验证 (A + B)^T = A^T + B^T。
用代码验证 (AB)^T = B^T A^T。'''

'一、综合应用\n构造一个 3 x 3 矩阵，并判断它是否为对称矩阵。\n构造一个 2 x 2 矩阵，计算它的行列式。\n找出一个矩阵的主对角线元素。\n用代码验证 (A + B)^T = A^T + B^T。\n用代码验证 (AB)^T = B^T A^T。'

In [61]:
x=torch.tensor([[1,2,3],[2,4,6],[3,6,9]])
x==x.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [66]:
y=torch.tensor([[1,2],[5,7]])
y.float().det(),torch.det(y.float())

(tensor(-3.), tensor(-3.))

In [67]:
print(torch.diag(x))

tensor([1, 4, 9])


In [70]:
x1=x
x2=torch.ones_like(x)
(x1+x2).T==x1.T+x2.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [72]:
(x1@x2).T==x1.T@x2.T,(x1@x2).T==x2.T@x1.T

(tensor([[ True, False, False],
         [False,  True, False],
         [False, False,  True]]),
 tensor([[True, True, True],
         [True, True, True],
         [True, True, True]]))

In [73]:
'''
为什么矩阵乘法不满足交换律？
为什么线性代数是机器学习的基础？
向量的点积为什么和角度有关？
为什么很多模型训练都离不开矩阵运算？
结合实际任务，说明掌握线性代数的意义。'''

'''
矩阵乘法依赖顺序和维度，交换顺序通常会改变结果
线性代数是特征表示、优化和神经网络计算的核心
点积与夹角余弦相关
模型本质上大量依赖矩阵乘法
它直接影响数据建模、参数更新和模型表达能力
'''

'\n矩阵乘法依赖顺序和维度，交换顺序通常会改变结果\n线性代数是特征表示、优化和神经网络计算的核心\n点积与夹角余弦相关\n模型本质上大量依赖矩阵乘法\n它直接影响数据建模、参数更新和模型表达能力\n'