In [1]:
# 链式发展
# 标量对列向量求导是行向量
# 自动求导：计算一个函数在指定值上的导数
# 计算图，等价链式法则求导的过程



In [2]:
import torch

In [22]:
x=torch.arange(4, dtype=torch.float)
x

tensor([0., 1., 2., 3.])

In [23]:
# 计算y关于x的梯度之前，需要一个地方存储梯度
x.requires_grad_(True)
x.grad

In [24]:
y=2*torch.dot(x,x)
y

tensor(28., grad_fn=<MulBackward0>)

In [25]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [29]:
x.grad==4*x

tensor([True, True, True, True])

In [36]:
# 默认梯度不会清除，会累加，因此如果执行两次 y.backward(), 得到的x.grad会是 8x
# 采用grad.zero_()清除梯度
x.grad.zero_()

tensor([0., 0., 0., 0.])

In [37]:
y=x.sum() # x1+x2+x3+x4
y.backward()
x.grad

tensor([1., 1., 1., 1.])

In [46]:
# 深度学习很少对 矩阵求导，也就是y 一般都是标量，而非矩阵、向量，如果y是非标量，通常会用 y=y.sum()，求和之后变成各元素之和的标量，再求导
# 因为loss一般就是标量

x.grad.zero_()

tensor([0., 0., 0., 0.])

In [47]:
y=x*x
u=y.detach() # 这一步是在说，u跟y值一样，但是u不和y一样，u将被视为和x无关的常量。
z=u*x
z.sum().backward()  # 这里z是一个向量，因此采用求和再梯度
x.grad==u

tensor([True, True, True, True])

In [65]:
# 复杂的函数也同样可以求导
def f(a):
    b=2*a
    while b.norm() < 1000: # 二范数小于1000
        b *=2
    if b.sum() > 0:
        c=b
    else:
        c=100*b
    return c
a=torch.randn(size=(),requires_grad=True)  # size=（），就是标量
d=f(a)
d.backward()

a.grad== d/a

tensor(True)