In [1]:
import torch

In [3]:
'''
二、代码题

1. 使用 PyTorch 创建一个 `2 x 3` 的全 0 张量。
2. 创建一个 `3 x 3` 的全 1 张量。
3. 创建一个从 `0` 到 `11` 的一维张量。
4. 把上题的一维张量变形成 `3 x 4` 矩阵。
5. 生成一个随机的 `2 x 2` 张量并打印其 shape。'''

'\n二、代码题\n\n1. 使用 PyTorch 创建一个 `2 x 3` 的全 0 张量。\n2. 创建一个 `3 x 3` 的全 1 张量。\n3. 创建一个从 `0` 到 `11` 的一维张量。\n4. 把上题的一维张量变形成 `3 x 4` 矩阵。\n5. 生成一个随机的 `2 x 2` 张量并打印其 shape。'

In [4]:
# 1
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [5]:
# 2
torch.ones(3,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [8]:
# 3
torch.arange(12)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [9]:
# 4
torch.arange(12).reshape([3,4])

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [10]:
torch.rand(2,2).shape

torch.Size([2, 2])

In [12]:
'''
### 三、索引题

1. 给定一个 `3 x 4` 张量，取出第 2 行。
2. 给定一个 `3 x 4` 张量，取出第 3 列。
3. 取出左上角 `2 x 2` 子矩阵。
4. 修改张量中第 1 行第 2 列的元素。
5. 用切片把前两行都改成全 9。'''

'\n### 三、索引题\n\n1. 给定一个 `3 x 4` 张量，取出第 2 行。\n2. 给定一个 `3 x 4` 张量，取出第 3 列。\n3. 取出左上角 `2 x 2` 子矩阵。\n4. 修改张量中第 1 行第 2 列的元素。\n5. 用切片把前两行都改成全 9。'

In [15]:
a=torch.randn(3,4)

a


tensor([[-0.3084, -0.1637, -0.2763,  0.1940],
        [ 0.8939, -0.3265,  0.3992,  1.4175],
        [-0.2350, -1.1339, -2.0743, -0.4850]])

In [16]:
# 3.1
a[1,:]

tensor([ 0.8939, -0.3265,  0.3992,  1.4175])

In [17]:
# 3.2
a[:,2]

tensor([-0.2763,  0.3992, -2.0743])

In [18]:
# 3.3
a[:2,:2]

tensor([[-0.3084, -0.1637],
        [ 0.8939, -0.3265]])

In [19]:
# 3.4
a[0,1]=3.1415926
a

tensor([[-0.3084,  3.1416, -0.2763,  0.1940],
        [ 0.8939, -0.3265,  0.3992,  1.4175],
        [-0.2350, -1.1339, -2.0743, -0.4850]])

In [20]:
a[:2,:]=9
a

tensor([[ 9.0000,  9.0000,  9.0000,  9.0000],
        [ 9.0000,  9.0000,  9.0000,  9.0000],
        [-0.2350, -1.1339, -2.0743, -0.4850]])